apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
spec:
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: nginx-green
        image: ediplo/green:latest
        ports:
        - containerPort: 8080
  
---

apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  selector:
    app: green
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-green
spec:
  ingressClassName: nginx
  rules:
  - host: green.eazyops.com.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: green-service
            port:
              number: 80

